// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"your-module-name/api/controller"
	"your-module-name/api/router"
	"your-module-name/common/middleware"
	"your-module-name/dal/cache"
	"your-module-name/dal/dao"
	"your-module-name/logic/service"
	"your-module-name/logic/repository"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp() *gin.Engine {
	demoDAOV1 := dao.NewDemoDAO()
	demoCacheV1 := cache.NewCacheV1()
	demoDomainServiceV1 := domainService.NewDemoDomainServiceV1(demoDAOV1, demoCacheV1)
	demoAppServiceV1 := appService.NewDemoAppServiceV1(demoDomainServiceV1)
	buildController := controller.NewBuildController(demoAppServiceV1)
	v := middleware.GetHandlerFunc()
	engine := router.RegisterRoutersAndMiddleware(buildController, v...)
	return engine
}
